# Copyright 2018 Dan Jacques. All rights reserved.
# Use of this source code is governed under the MIT License
# that can be found in the LICENSE file.

language: go

go:
  - 1.9
  - tip

before_install:
  - go get github.com/maruel/pre-commit-go/cmd/pcg

install:
  - go get -t ./...

script:
  - pcg
